TestWebApp/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using TestWebApp.Interfaces;
using TestWebApp.ViewModels;

namespace TestWebApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _service;
        private readonly IUserMapper _mapper;

        public AuthController(IUserService userService, IUserMapper mapper)
        {
            _service = userService;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginViewModel loginResponse)
        {
            
            if (ModelState.IsValid)
            {

                var result = await _service.SignIn(loginResponse);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError(string.Empty, "Invalid Login Attempt");
            } 

            // Authentication fails
            return View(loginResponse);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _service.SignOut();

            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterViewModel registerResponse)
        {
            Dictionary<string, string> messages = new Dictionary<string, string>();

            if (ModelState.IsValid)
            {
                var result = await _service.CreateAsync(registerResponse);

                if (result.Succeeded)
                {
                    await _service.SignIn(registerResponse);
                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                foreach (KeyValuePair<string, string> entry in messages)
                {
                    ModelState.AddModelError(entry.Key, entry.Value);
                }

                ModelState.AddModelError(string.Empty, "Invalid Registration Attempt");
            }

            // Registration fails
            return View(registerResponse);
        }
    }
}

TestWebApp/Controllers/PostController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestWebApp.Interfaces;
using TestWebApp.Mappers;
using TestWebApp.Models;
using TestWebApp.Services;
using TestWebApp.Utilities;
using TestWebApp.ViewModels;

namespace TestWebApp.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _service;
        private IPostMapper _mapper;

        public PostController(IPostService postService, IPostMapper mapper)
        {
            _service = postService;
            _mapper = mapper;
        }

        // GET: Post
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _service.ToListAsync());

            //return View(await _mapper.Posts.ToListAsync());
        }

        // GET: Post/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string? slug)
        {
           
            if (slug == null)
            {
                return NotFound();
            }

            var post = await _service.GetPostVMAsync(slug);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Post/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostCreateViewModel post)
        {
            var username = User.Identity.GetUserName();
                post.UserName = username;

            if (ModelState.IsValid)
            {
                await _service.CreateAsync(post);
                return RedirectToAction(nameof(Index));
            }
            
            return View(post);
        }

        // GET: Post/Edit/slug
        [Authorize]
        public async Task<IActionResult> Edit(string? slug)
        {
            if (slug == null)
            {
                return NotFound();
            }

            var post = await _service.GetPostCreateVMAsync(slug);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string slug, PostCreateViewModel post)
        {
            if (slug != post.Slug)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    post.UserName = User.Identity.GetUserName();
                    await _service.UpdateAsync(post);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! _service.Exists(slug))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Post/Delete/slug
        [Authorize]
        public async Task<IActionResult> Delete(string slug)
        {
            if (slug == null)
            {
                return NotFound();
            }

            var post = await _service.GetPostVMAsync(slug);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Post/Delete/slug
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string slug)
        {
            await _service.DeleteAsync(slug);
            return RedirectToAction(nameof(Index));
        }
    }
}

TestWebApp/Controllers/UserController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestWebApp.Models;
using TestWebApp.ViewModels;
using TestWebApp.Utilities;
using Microsoft.AspNetCore.Authorization;
using TestWebApp.Interfaces;

namespace TestWebApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _service;
        private readonly IUserMapper _mapper;

        public UserController(IUserService userService, IUserMapper mapper)
        {
            _service = userService;
            _mapper = mapper;
        }

        // GET: User
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _service.ToListAsync());
        }

        // GET: User/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string? username)
        {
            if (username == null)
            {
                return NotFound();
            }

            var user = await _service.GetUserVMAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: User/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(UserRegisterViewModel user)
        {
            Dictionary<string, string> messages = new Dictionary<string, string>();

            if (ModelState.IsValid)
            {
                var result = await _service.CreateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(user);
        }

        // GET: User/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string? username)
        {
            if (username == null)
            {
                return NotFound();
            }

            var user = await _service.GetUserRegisterVMAsync(username);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(string username, UserRegisterViewModel user)
        {
            if (username != user.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var updateResult = await _service.UpdateAsync(user);
                    if (updateResult)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    ModelState.AddModelError(String.Empty, "Database error");
                }
                catch (DbUpdateConcurrencyException)
                {
                    var userExist = await _service.Exists(username);
                    if (!userExist)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(user);
        }

        // GET: User/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string? username)
        {
            if (username == null)
            {
                return NotFound();
            }

            var user = await _service.GetUserVMAsync(username);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string username)
        {
            await _service.DeleteAsync(username);
            return RedirectToAction(nameof(Index));
        }
    }
}

TestWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        } else {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>